
# sample_ctp <- read.table(
#   "/broad/bican_um1_mccarroll/RNAseq/analysis/CAP_freeze_3_analysis/cell_type_proportions/LEVEL_1/donor_region.annotation.cell_type_proportions.txt",
#   sep="\t", header=TRUE, stringsAsFactors = FALSE
# )
#
# ratio_df <- generate_ctp_ratio_table(
#   sample_ctp,
#   numerator=c("MSN_D1_matrix", "MSN_D1_striosome"),
#   denominator=c("MSN_D2_matrix", "MSN_D2_striosome")
# )
#
# plot_donor_ctp_ratio_between_two_regions(ratio_df, "CaH", "Pu", "D1/D2 MSN ratio")
#


#' Generate Cell-Type Proportion (CTP) Ratio Table
#'
#' This function calculates ratios between specific cell-type populations across
#' defined brain regions. It allows for the comparison of a subset of cells
#' (numerator) against either another subset or the total nuclei count (denominator).
#'
#' @param ctp_df A data frame containing cell type counts. Must include columns:
#'   `brain_region_abbreviation_simple`, `sample_id`, `donor_external_id`,
#'   `total_nuclei`, `n_nuclei`, and the column specified in `cell_type_col`.
#' @param numerator A character vector of cell type names to be summed for the numerator.
#' @param denominator A character vector of cell type names to be summed for the denominator.
#'   If `NULL`, the total nuclei count for the sample/region is used as the denominator.
#' @param cell_type_col Character string specifying the column name in `ctp_df`
#'   that contains cell type annotations. Defaults to `"annotation"`.
#' @param region_list A character vector of brain regions to include in the analysis.
#'   Defaults to `c("CaH", "Pu", "NAC")`.
#'
#' @return A tibble (data frame) containing `sample_id`, `brain_region_abbreviation_simple`,
#'   `donor_external_id`, `total_nuclei`, and the calculated `ratio`.
#'
#' @importFrom dplyr filter group_by summarise mutate select .data
#' @export
generate_ctp_ratio_table <- function(
    ctp_df,
    numerator,
    denominator,
    cell_type_col = "annotation",
    region_list = c("CaH", "Pu", "NAC"))
{

  ratio_df <- ctp_df |>
    # Filter to brain regions of interest
    dplyr::filter(.data$brain_region_abbreviation_simple %in% region_list) |>

    # Group by sample_id
    dplyr::group_by(
      .data$sample_id,
      .data$brain_region_abbreviation_simple,
      .data$donor_external_id,
      .data$total_nuclei
    ) |>

    # Calculate sums for numerator and denominator subsets
    dplyr::summarise(
      # Sum nuclei for cell types defined in 'numerator'
      numerator_sum = sum(
        .data$n_nuclei[.data[[cell_type_col]] %in% numerator],
        na.rm = TRUE
      ),

      # If denominator is NULL, use all nuclei in the group; otherwise, sum specific subset
      denominator_sum = if (is.null(denominator)) {
        sum(.data$n_nuclei, na.rm = TRUE)
      } else {
        sum(
          .data$n_nuclei[.data[[cell_type_col]] %in% denominator],
          na.rm = TRUE
        )
      },
      .groups = "drop"
    ) |>

    # Compute the final ratio
    dplyr::mutate(ratio = .data$numerator_sum / .data$denominator_sum) |>

    # Return columns needed for plotting
    dplyr::select(
      .data$sample_id,
      .data$brain_region_abbreviation_simple,
      .data$donor_external_id,
      .data$total_nuclei,
      .data$ratio
    )

  return(ratio_df)
}


#' Scatterplot of donor CTP ratio between two regions.
#'
#' @param ratio_df Dataframe containing CTP ratios for each donor and brain region,
#' as generated by `generate_ctp_ratio_table()`.
#' @param region1 Region to plot on x-axis.
#' @param region2 Region to plot on y-axis.
#' @param ratio (optional) Name of the ratio being plotted (for labeling).
plot_donor_ctp_ratio_between_two_regions <- function(ratio_df, region1, region2, ratio=NULL) {

# -------------------------------------------------------------------------


  ratio_df_wide <- ratio_df |>
    select(donor_external_id, brain_region_abbreviation_simple, ratio) |>
    pivot_wider(
      names_from = brain_region_abbreviation_simple,
      values_from = ratio
    )

  plot_df <- ratio_df_wide |>
    select(donor_external_id, !!sym(region1), !!sym(region2)) |>
    na.omit()

  n_donors <- nrow(plot_df)

  min_ratio <- min(unlist(plot_df[sapply(plot_df, is.numeric)]), na.rm = TRUE)
  max_ratio <- max(unlist(plot_df[sapply(plot_df, is.numeric)]), na.rm = TRUE)

  ggplot(
    plot_df,
    aes(x = !!sym(region1), y = !!sym(region2))
  ) +
    theme_bw() +
    geom_abline(slope=1, intercept=0, lty="dashed", col="gray") +
    geom_point() +
    labs(
      title=ratio,
      subtitle=sprintf("N=%s donors", n_donors)
    ) +
    xlim(min_ratio, max_ratio) +
    ylim(min_ratio, max_ratio)

}


