name: Python unit tests for bican_mccarroll_helloworld

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'python/bican_mccarroll_helloworld/**'


jobs:
  call-python-reusable:
    uses: ./.github/workflows/python-reusable.yml
    with:
      package_name: bican_mccarroll_helloworld
    secrets: inherit
