# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    paths:
      - 'R/bican.mccarroll.helloworld/**'

name: Build and check R bican.mccarroll.helloworld package


jobs:
  call-R-reusable:
    uses: ./.github/workflows/R-reusable.yml
    with:
      package_name: bican.mccarroll.helloworld
    secrets: inherit
