# Workflow derived from dplyr/.github/workflows/pr-commands.yaml
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  issue_comment:
    types: [created]
    paths:
      - 'R/bican.mccarroll.helloworld/**'

name: Run roxygen2 on R package bican.mccarroll.helloworld and commit changes

permissions: read-all

jobs:
  call-roxygen-reusable:
    uses: ./.github/workflows/roxygen-reusable.yml
    with:
      package_name: bican.mccarroll.helloworld
    secrets: inherit
